"""empty message

Revision ID: 07b13434c3c1
Revises: 9c153b94d76c
Create Date: 2022-07-25 12:44:01.034028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b13434c3c1'
down_revision = '9c153b94d76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('future_shows', sa.PickleType(), nullable=True))
    op.add_column('Artist', sa.Column('previous_shows', sa.PickleType(), nullable=True))
    op.add_column('Artist', sa.Column('previous_shows_count', sa.Integer(), nullable=True))
    op.add_column('Artist', sa.Column('future_shows_count', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('future_shows', sa.PickleType(), nullable=True))
    op.add_column('Venue', sa.Column('previous_shows', sa.PickleType(), nullable=True))
    op.add_column('Venue', sa.Column('previous_shows_count', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('future_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'future_shows_count')
    op.drop_column('Venue', 'previous_shows_count')
    op.drop_column('Venue', 'previous_shows')
    op.drop_column('Venue', 'future_shows')
    op.drop_column('Artist', 'future_shows_count')
    op.drop_column('Artist', 'previous_shows_count')
    op.drop_column('Artist', 'previous_shows')
    op.drop_column('Artist', 'future_shows')
    # ### end Alembic commands ###
